defaults:
  - default
  - _self_

train_algorithm: "vscrl" # "vscrl", should be same as the evaluation checkpoint
save_path: '/home/<username>/logs/vscrl-general-online/'

# training
task_mode: "evaluate" # "train" or "evaluate" - "train" will do training when evaluating, "evaluate" will NOT do training
parallel: "single" # "single" or "host" or "worker"

# train_iterations: 400
eval_iterations: 6
save_freq: 3